# Use custom format
format = """
[â•­â”€\\(](bold black)$username[\\[](bold cyan)[ğŸ’€](bold cyan)[\\]](bold cyan)$hostname[\\)â”€](bold black)$directory $all
[â•°â”€](bold black)$character"""

# Don't print a new line at the start of the prompt
add_newline = true

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
#success_symbol = "[ó°‰ğŸ¼ğŸ’€ğŸ’£ğŸ§¨ğŸ§§ğŸ“œğŸª™ğŸª›ğŸš¬ğŸ’¢](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
success_symbol = "[\\$](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"

[git_branch]
always_show_remote = false
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = 'î‚  '
style = 'bold purple'
#truncation_length = 10
truncation_symbol = 'â€¦'
only_attached = false
#ignore_branches = ['master', 'main']
disabled = false

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
#conflicted = 'ğŸ³'
#ahead = 'ğŸğŸ’¨'
#behind = 'ğŸ˜°'
#diverged = 'ğŸ˜µ'
#up_to_date = 'âœ“'
#untracked = 'ğŸ¤· '
#stashed = 'ğŸ“¦'
#modified = ' ğŸ“ '
#staged = '[++\($count\)](green)'
#renamed = 'ğŸ‘…'
#deleted = 'ğŸ—‘ '

[username]
style_user = "bold red underline"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
style = "bold blue underline"
ssh_only = false
format = "[$hostname]($style)"
trim_at = "-"
disabled = false

[directory]
format="[$read_only]($read_only_style)[\\[](bold black)[$path]($style)[\\]](bold black)"
style="blue bold"
read_only = " ó°‰ "
read_only_style="red bold"
truncation_symbol=""
truncation_length= 10
truncate_to_repo = false
#repo_root_style="($style)"
repo_root_format="[$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
home_symbol="~"

[time]
time_format = "%T"
format = "ğŸ•™ $time($style) "
style = "bright-white"
disabled = true

