# Use custom format
format = """
[â•­â”€](bold black)$username$hostname$directory $all
[â•°â”€](bold black)$character"""

#format = """
#[â•­â”€\\(](bold black)$username[\\[](bold cyan)[ğŸ’€](bold cyan)[\\]](bold cyan)$hostname[\\)â”€](bold black)$directory $all
#[â•°â”€](bold black)$character"""

# Don't print a new line at the start of the prompt
add_newline = true

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# ~/.config/starship.toml

[cmd_duration]
min_time = 500
format = '[$duration](bold yellow)'

[sudo]
style = 'bold green'
symbol = 'ğŸ‘©â€ğŸ’» '
disabled = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]
#ó°‰ ğŸ¼ğŸ’€ğŸ’£ğŸ§¨ğŸ§§ğŸ“œğŸª™ğŸª›ğŸâš¡ğŸª²ğŸºğŸ»ğŸš¬ğŸ’¢ãŠ™ï¸ğŸ‘¹
success_symbol = "[ğŸ¼](bold green)"
error_symbol = "[ğŸ’¢](bold red)"


[username]
style_user = "bold yellow"
style_root = "red bold"
format = "[\\(](bold black)[$user]($style)[ğŸ§¨](bold red)"
disabled = false
show_always = true

[hostname]
style = "bold yellow"
ssh_only = false
format = '[$hostname]($style)[\)-](bold black)'
trim_at = "-"
disabled = false

[directory]
format="[$read_only]($read_only_style)[\\[](bold black)[$path]($style)[\\]](bold black)"
style="bold blue"
read_only = " ó°‰ "
read_only_style="red bold"
truncation_symbol=""
truncation_length= 10
truncate_to_repo = false
#repo_root_style="($style)"
repo_root_format="[$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
home_symbol="~"

[git_branch]
always_show_remote = false
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = 'î‚  '
style = 'bold purple'
#truncation_length = 10
truncation_symbol = 'â€¦'
only_attached = false
#ignore_branches = ['master', 'main']
disabled = false

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[time]
time_format = "%T"
format = "ğŸ•™ $time($style) "
style = "bright-white"
disabled = true

